#!/usr/bin/env python3
#
# Software License Agreement (BSD License)
#
# Copyright (c) 2012-2014, Southwest Research Institute
# Copyright (c) 2014-2015, TU Delft Robotics Institute
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#  * Neither the name of the Southwest Research Institute, nor the names
#    of its contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

import copy
import queue
import threading
import time

import rclpy
from rclpy.duration import Duration
from rclpy.node import Node

# Publish
from sensor_msgs.msg import JointState
from control_msgs.msg import FollowJointTrajectoryFeedback
from industrial_msgs.msg import RobotStatus

# Subscribe
from trajectory_msgs.msg import JointTrajectory
from trajectory_msgs.msg import JointTrajectoryPoint

# Services
from industrial_msgs.srv import GetRobotInfo

# Reference
from industrial_msgs.msg import TriState, RobotMode, ServiceReturnCode, DeviceInfo


class MotionControllerSimulator():
    """
    Simulates the motion controller for an industrial robot.

    This class IS threadsafe.
    """

    def __init__(self, node, num_joints, initial_joint_state, update_rate=100, buffer_size=0):
        self.node = node
        self.lock = threading.Lock()

        self.update_rate = update_rate
        node.get_logger().debug('Setting motion update rate (hz): %f' % self.update_rate)

        self.joint_positions = initial_joint_state
        node.get_logger().debug('Setting initial joint state: %s' % str(initial_joint_state))

        self.motion_buffer = queue.Queue(buffer_size)
        node.get_logger().debug('Setting motion buffer size: %i' % buffer_size)

        self.sig_shutdown = False
        self.sig_stop = False

        self.motion_thread = threading.Thread(target=self._motion_worker)
        self.motion_thread.daemon = True
        self.motion_thread.start()

    def add_motion_waypoint(self, point):
        self.motion_buffer.put(point)

    def get_joint_positions(self):
        with self.lock:
            return self.joint_positions[:]

    def is_in_motion(self):
        return not self.motion_buffer.empty()

    def shutdown(self):
        self.sig_shutdown = True
        self.node.get_logger().debug('Motion_Controller shutdown signaled')

    def stop(self):
        self.node.get_logger().debug('Motion_Controller stop signaled')
        with self.lock:
            self._clear_buffer()
            self.sig_stop = True

    def interpolate(self, last_pt, current_pt, alpha):
        intermediate_pt = JointTrajectoryPoint()
        for last_joint, current_joint in zip(last_pt.positions, current_pt.positions):
            intermediate_pt.positions.append(last_joint + alpha * (current_joint - last_joint))
        last_sec = Duration.from_msg(last_pt.time_from_start).nanoseconds / 1e9
        current_sec = Duration.from_msg(current_pt.time_from_start).nanoseconds / 1e9
        intermediate_pt.time_from_start = Duration(
            seconds=last_sec + alpha * (current_sec - last_sec)).to_msg()
        return intermediate_pt

    def accelerate(self, last_pt, current_pt, current_time, delta_time):
        intermediate_pt = JointTrajectoryPoint()
        for last_joint, current_joint, last_vel, current_vel in zip(
                last_pt.positions, current_pt.positions, last_pt.velocities, current_pt.velocities):
            delta_x = current_joint - last_joint
            dv = current_vel + last_vel
            a1 = 6 * delta_x / pow(delta_time, 2) - 2 * (dv + last_vel) / delta_time
            a2 = -12 * delta_x / pow(delta_time, 3) + 6 * dv / pow(delta_time, 2)
            current_pos = (last_joint + last_vel * current_time + a1 * pow(current_time, 2) / 2
                           + a2 * pow(current_time, 3) / 6)
            intermediate_pt.positions.append(current_pos)
        last_sec = Duration.from_msg(last_pt.time_from_start).nanoseconds / 1e9
        intermediate_pt.time_from_start = Duration(seconds=last_sec + current_time).to_msg()
        return intermediate_pt

    def _clear_buffer(self):
        with self.motion_buffer.mutex:
            self.motion_buffer.queue.clear()

    def _move_to(self, point, dur_sec):
        time.sleep(max(dur_sec, 0.0))

        with self.lock:
            if not self.sig_stop:
                self.joint_positions = point.positions[:]
            else:
                self.node.get_logger().debug('Stopping motion immediately, clearing stop signal')
                self.sig_stop = False

    def _motion_worker(self):
        self.node.get_logger().debug('Starting motion worker in motion controller simulator')
        last_goal_point = JointTrajectoryPoint()

        with self.lock:
            last_goal_point.positions = self.joint_positions[:]

        update_duration_sec = 1. / self.update_rate if self.update_rate != 0. else 0.0

        while not self.sig_shutdown:
            try:
                current_goal_point = self.motion_buffer.get()

                current_start_sec = Duration.from_msg(current_goal_point.time_from_start).nanoseconds / 1e9
                last_start_sec = Duration.from_msg(last_goal_point.time_from_start).nanoseconds / 1e9

                # If the current time from start is less than the last, then it's a new trajectory
                if current_start_sec < last_start_sec:
                    move_duration_sec = current_start_sec
                # Else it's an existing trajectory and subtract the two
                else:
                    move_duration_sec = current_start_sec - last_start_sec
                    if self.update_rate > 0:
                        starting_goal_point = copy.deepcopy(last_goal_point)
                        full_duration = move_duration_sec
                        while update_duration_sec < move_duration_sec:
                            if not starting_goal_point.velocities or not current_goal_point.velocities:
                                intermediate_goal_point = self.interpolate(
                                    last_goal_point, current_goal_point,
                                    update_duration_sec / move_duration_sec)
                            else:
                                intermediate_goal_point = self.accelerate(
                                    starting_goal_point, current_goal_point,
                                    full_duration - move_duration_sec + update_duration_sec,
                                    full_duration)
                            self._move_to(intermediate_goal_point, update_duration_sec)
                            last_goal_point = copy.deepcopy(intermediate_goal_point)
                            intermediate_start_sec = Duration.from_msg(
                                intermediate_goal_point.time_from_start).nanoseconds / 1e9
                            move_duration_sec = current_start_sec - intermediate_start_sec

                self._move_to(current_goal_point, move_duration_sec)
                last_goal_point = copy.deepcopy(current_goal_point)

            except Exception as e:
                self.node.get_logger().error('Unexpected exception: %s' % e)

        self.node.get_logger().debug('Shutting down motion controller')


class IndustrialRobotSimulatorNode(Node):
    """
    Simulates an industrial robot controller.

    The simulator adheres to the ROS-Industrial robot driver specification:
    http://www.ros.org/wiki/Industrial/Industrial_Robot_Driver_Spec

    TODO: Currently the simulator only supports the bare minimum motion
    interface.

    TODO: Interfaces to add:
    Joint streaming
    All services
    """

    def __init__(self):
        super().__init__('industrial_robot_simulator')

        self.lock = threading.Lock()

        self.declare_parameter('pub_rate', 10.0)
        self.pub_rate = self.get_parameter('pub_rate').value
        self.get_logger().debug('Setting publish rate (hz) based on parameter: %f' % self.pub_rate)

        def_joint_names = ['joint_1', 'joint_2', 'joint_3', 'joint_4', 'joint_5', 'joint_6']
        self.declare_parameter('controller_joint_names', def_joint_names)
        self.joint_names = self.get_parameter('controller_joint_names').value
        if len(self.joint_names) == 0:
            self.get_logger().warn(
                "Joint list is empty, did you set the 'controller_joint_names' parameter?")
        self.get_logger().info('Simulating manipulator with %d joints: %s' % (
            len(self.joint_names), ', '.join(self.joint_names)))

        num_joints = len(self.joint_names)
        self.declare_parameter('initial_joint_state', [0.0] * num_joints)
        initial_joint_state = self.get_parameter('initial_joint_state').value
        same_len = len(initial_joint_state) == num_joints
        all_num = all(isinstance(x, (int, float)) for x in initial_joint_state)
        if not same_len or not all_num:
            initial_joint_state = [0.0] * num_joints
            self.get_logger().warn(
                'Invalid initial_joint_state parameter, defaulting to all-zeros '
                '(len: %s, types: %s).' % (same_len, all_num))
        self.get_logger().info('Using initial joint state: %s' % str(initial_joint_state))

        self.declare_parameter('motion_update_rate', 100.0)
        motion_update_rate = self.get_parameter('motion_update_rate').value
        self.motion_ctrl = MotionControllerSimulator(
            self, num_joints, initial_joint_state, update_rate=motion_update_rate)

        self.get_logger().debug('Creating joint state publisher')
        self.joint_state_pub = self.create_publisher(JointState, 'joint_states', 1)

        self.get_logger().debug('Creating joint feedback publisher')
        self.joint_feedback_pub = self.create_publisher(
            FollowJointTrajectoryFeedback, 'feedback_states', 1)

        self.get_logger().debug('Creating robot status publisher')
        self.robot_status_pub = self.create_publisher(RobotStatus, 'robot_status', 1)

        self.get_logger().debug('Creating joint trajectory subscriber')
        self.joint_path_sub = self.create_subscription(
            JointTrajectory, 'joint_path_command', self.trajectory_callback, 1)

        period = 1.0 / self.pub_rate
        self.get_logger().debug('Setting up publish worker with period (sec): %s' % str(period))
        self.publish_timer = self.create_timer(period, self.publish_worker)

        self.declare_parameter('robot_info', '')
        self.get_robot_info_response = self._init_robot_info_response()
        self.svc_get_robot_info = self.create_service(
            GetRobotInfo, 'get_robot_info', self.cb_svc_get_robot_info)

    def cb_svc_get_robot_info(self, request, response):
        return self.get_robot_info_response

    def publish_worker(self):
        self.joint_state_publisher()
        self.robot_status_publisher()

    def joint_state_publisher(self):
        try:
            joint_state_msg = JointState()
            joint_fb_msg = FollowJointTrajectoryFeedback()
            time_now = self.get_clock().now().to_msg()

            with self.lock:
                joint_state_msg.header.stamp = time_now
                joint_state_msg.name = self.joint_names
                joint_state_msg.position = self.motion_ctrl.get_joint_positions()

                self.joint_state_pub.publish(joint_state_msg)

                joint_fb_msg.header.stamp = time_now
                joint_fb_msg.joint_names = self.joint_names
                joint_fb_msg.actual.positions = self.motion_ctrl.get_joint_positions()

                self.joint_feedback_pub.publish(joint_fb_msg)

        except Exception as e:
            self.get_logger().error('Unexpected exception in joint state publisher: %s' % e)

    def robot_status_publisher(self):
        try:
            msg = RobotStatus()
            msg.mode.val = RobotMode.AUTO
            msg.e_stopped.val = TriState.FALSE
            msg.drives_powered.val = TriState.TRUE
            msg.motion_possible.val = TriState.TRUE
            msg.in_motion.val = self.motion_ctrl.is_in_motion()
            msg.in_error.val = TriState.FALSE
            msg.error_code = 0
            self.robot_status_pub.publish(msg)

        except Exception as e:
            self.get_logger().error('Unexpected exception: %s' % e)

    def trajectory_callback(self, msg_in):
        try:
            self.get_logger().debug(
                'Received trajectory with %s points, executing callback' % str(len(msg_in.points)))

            if self.motion_ctrl.is_in_motion():
                if len(msg_in.points) > 0:
                    self.get_logger().error(
                        'Received trajectory while still in motion, trajectory splicing not supported')
                else:
                    self.get_logger().debug(
                        'Received empty trajectory while still in motion, stopping current trajectory')
                self.motion_ctrl.stop()

            else:
                for point in msg_in.points:
                    point = self._to_controller_order(msg_in.joint_names, point)
                    self.motion_ctrl.add_motion_waypoint(point)

        except Exception as e:
            self.get_logger().error('Unexpected exception: %s' % e)

        self.get_logger().debug('Exiting trajectory callback')

    def _to_controller_order(self, keys, point):
        pt_rtn = copy.deepcopy(point)
        pt_rtn.positions = self._remap_order(self.joint_names, keys, point.positions)
        if point.velocities:
            pt_rtn.velocities = self._remap_order(self.joint_names, keys, point.velocities)

        return pt_rtn

    def _remap_order(self, ordered_keys, value_keys, values):
        ordered_values = [0] * len(ordered_keys)
        mapping = dict(zip(value_keys, values))

        for i in range(len(ordered_keys)):
            ordered_values[i] = mapping[ordered_keys[i]]

        return ordered_values

    def _init_robot_info_response(self):
        robot_info_param = self.get_parameter('robot_info').value
        if not robot_info_param:
            irs_version = '0.7.3'
            try:
                import xml.etree.ElementTree as ET
                from ament_index_python.packages import get_package_share_directory
                package_xml = get_package_share_directory(
                    'industrial_robot_simulator') + '/package.xml'
                irs_version = ET.parse(package_xml).getroot().find('version').text
            except Exception:
                pass
            robot_info = dict(
                controller=dict(
                    model='Industrial Robot Simulator Controller',
                    serial_number='0123456789',
                    sw_version=irs_version),
                robots=[
                    dict(
                        model='Industrial Robot Simulator Manipulator',
                        serial_number='9876543210',
                        sw_version=irs_version)
                ])
        else:
            robot_info = robot_info_param

        resp = GetRobotInfo.Response()
        resp.controller = DeviceInfo(**robot_info['controller'])

        if len(robot_info['robots']) > 0:
            robot = robot_info['robots'][0]
            resp.robots.append(DeviceInfo(**robot))

        if len(robot_info['robots']) > 1:
            self.get_logger().warn(
                "Multiple robots / motion groups defined in 'robot_info' parameter, "
                'ignoring all but first element')

        resp.code.val = ServiceReturnCode.SUCCESS
        return resp


def main(args=None):
    rclpy.init(args=args)
    try:
        node = IndustrialRobotSimulatorNode()
        node.get_logger().info('Starting joint_controller_simulator')
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        rclpy.shutdown()


if __name__ == '__main__':
    main()
